import type { NextPage } from 'next'
import Head from 'next/head'
import { InputIk } from '../components/Input.stories'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>StoryBook</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        start
        <InputIk />
      </div>
      <div className='data'>
        <div className='ddd'>
          <div className='dadad'>
            <div className='fffa'>
              <div className='sss'>
                <div className='dadasd'>
                  <div className='dasd'>
                    <div className='dadaw'>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
