import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { InputIk } from '../components/Input.stories'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <link
          href='https://fonts.googleapis.com/css?family=Ubuntu:300,300italic,regular,italic,500,500italic,700,700italic'
          rel='stylesheet'
        />
        <title>StoryBook</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        start
        <InputIk />
      </div>
      <Image src='/myF.svg' width='400px' height='400px' />
    </div>
  )
}

export default Home
